### ISSUE TITLE
Create Header files

### ISSUE THREAD

**Issue by potatochick2020** [potatochick2020/Sudoku-core#1]
As what it stated ...

**Comment by potatochick2020** [comment]
Sure, But please wait for [Rename variable issues](https://github.com/potatochick2020/Sudoku-core/issues/4).

At the moment you can submit a draft pull request (google it if you have no idea what it is) and start your work when [Rename variable issues](https://github.com/potatochick2020/Sudoku-core/issues/4) is finish.

**Comment by WaniAthar** [comment]
no problem
